---
# This is an example playbook to execute Ansible tests.
# TODO delete. It's not used.
# testinfra is used
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    ansible.builtin.assert:
      that: true
